FROM ubuntu:18.04

MAINTAINER "Syed Saad Ahmed"

apt update
apt install software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt update

apt install python3-pip

pip3 install --upgrade pip

pip3 install numpy scikit-learn matplotlib

pip3 install tensorflow

pip3 install keras

pip3 install --upgrade tensorflow==2.2



